name: Run Base64 to Hex Script

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Git identity
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Use a specific version like '3.10' if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run the script
      run: |
        python convert_base64_to_hex.py

    - name: Pull latest
      run: git pull

    - name: Commit output_hex_file
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Conversion complete. Hex data written to output.txt"